@echo off
echo Running schema...
mysql -u root placement_records_db < sql\01_schema.sql
echo Running triggers...
mysql -u root placement_records_db < sql\02_triggers.sql
echo Running indexes...
mysql -u root placement_records_db < sql\03_indexes.sql
echo Running data...
mysql -u root placement_records_db < sql\04_data.sql
echo Done.
