-- ============================================================
-- PRMS — File 14: Move roll number generation to Java
--
-- What this does:
--   1. Drops the trg_assign_roll_no trigger. Roll numbers are now
--      generated by LocalRollNumberService in Java before INSERT.
--   2. Creates the roll_number_counters table — one row per
--      (dept_id, batch_year) combination, tracking the highest
--      serial issued so far.
--   3. Seeds the counters from the existing Students table so
--      the Java service picks up where the trigger left off.
--
-- IMPORTANT: After running this script, all student creation MUST
-- go through the application (API or DataInitializer). Direct SQL
-- INSERTs without an explicit roll_no will fail the NOT NULL
-- constraint, because the trigger no longer exists to fill it in.
-- Seed files 11 and 12 must be run BEFORE this migration.
--
-- Requires MySQL 8.0+ (for GROUP BY used in seeding step).
-- ============================================================

USE placement_records_db;

-- ── Step 1: Drop the trigger ─────────────────────────────────
-- Business logic (serial allocation) moves to Java.
DROP TRIGGER IF EXISTS trg_assign_roll_no;

-- ── Step 2: Create the counter table ─────────────────────────
-- Each row holds the highest serial number already issued for a
-- given department + batch-year combination.
-- UNIQUE on (dept_id, batch_year) prevents duplicate counters
-- if two threads try to create the first counter simultaneously.
CREATE TABLE IF NOT EXISTS roll_number_counters (
    id          BIGINT  NOT NULL AUTO_INCREMENT,
    dept_id     INT     NOT NULL,
    batch_year  INT     NOT NULL,
    last_serial INT     NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uq_counter_dept_batch (dept_id, batch_year),
    CONSTRAINT fk_counter_dept
        FOREIGN KEY (dept_id) REFERENCES Departments (dept_id)
        ON DELETE CASCADE
);

-- ── Step 3: Seed counters from current students ───────────────
-- last_serial = COUNT(*) within each group = the highest serial
-- that has already been issued (serials are 1-based and gapless).
-- The next student in that group will receive last_serial + 1.
INSERT INTO roll_number_counters (dept_id, batch_year, last_serial)
SELECT
    dept_id,
    batch_year,
    COUNT(*) AS last_serial
FROM Students
GROUP BY dept_id, batch_year
ON DUPLICATE KEY UPDATE last_serial = VALUES(last_serial);

-- ── Verify ───────────────────────────────────────────────────
-- Confirm one counter row per dept + batch combination, with
-- last_serial matching the student count in each group.
SELECT
    c.id,
    d.section,
    d.program,
    d.branch,
    c.batch_year,
    c.last_serial,
    COUNT(s.student_id) AS actual_students
FROM roll_number_counters c
JOIN Departments  d ON d.dept_id     = c.dept_id
JOIN Students     s ON s.dept_id     = c.dept_id
                   AND s.batch_year  = c.batch_year
GROUP BY c.id, d.section, d.program, d.branch, c.batch_year, c.last_serial
ORDER BY c.dept_id, c.batch_year;